#!/usr/bin/env node
/**
 * Build obfuscated static assets into ./release for the public Pages deploy.
 *
 * Source under src/, lib/, styles/, vendor/ stays readable in the public repo.
 * release/ is what GitHub Pages serves (harder casual reverse-engineering).
 *
 * Usage:
 *   node scripts/build-release.mjs
 *   node scripts/build-release.mjs --skip-obfuscate   # copy only (CI smoke)
 */

import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { minify } from "terser";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "release");
const skipObfuscate = process.argv.includes("--skip-obfuscate");

/** Shipped as-is (not mangled). Heavy PDK trees stay out of Pages. */
const COPY_AS_IS = ["index.html", ".nojekyll", "styles", "lib", "vendor"];

async function obfuscateJsFile(sourcePath, destPath) {
  const code = readFileSync(sourcePath, "utf8");
  if (skipObfuscate) {
    writeFileSync(destPath, code);
    return;
  }
  const result = await minify(code, {
    compress: { passes: 2, dead_code: true },
    mangle: { toplevel: true },
    format: { comments: false },
    module: true,
  });
  if (!result.code) {
    throw new Error(`terser produced empty output for ${sourcePath}`);
  }
  writeFileSync(destPath, result.code);
}

function walkJsFiles(dir, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walkJsFiles(full, acc);
    else if (name.endsWith(".js") || name.endsWith(".mjs")) acc.push(full);
  }
  return acc;
}

function copyTree(rel) {
  const from = path.join(root, rel);
  const to = path.join(outDir, rel);
  if (!existsSync(from)) return;
  mkdirSync(path.dirname(to), { recursive: true });
  cpSync(from, to, { recursive: true });
}

async function main() {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  for (const rel of COPY_AS_IS) {
    console.log(`copy ${rel}`);
    copyTree(rel);
  }

  // Lightweight models README only (not full PDK checkouts).
  const modelsReadme = path.join(root, "models", "README.md");
  if (existsSync(modelsReadme)) {
    mkdirSync(path.join(outDir, "models"), { recursive: true });
    cpSync(modelsReadme, path.join(outDir, "models", "README.md"));
  }

  const jsFiles = walkJsFiles(path.join(root, "src"));
  const digest = createHash("sha256");
  for (const file of jsFiles) {
    const rel = path.relative(root, file);
    const dest = path.join(outDir, rel);
    mkdirSync(path.dirname(dest), { recursive: true });
    console.log(`${skipObfuscate ? "copy" : "minify"} ${rel}`);
    await obfuscateJsFile(file, dest);
    digest.update(rel);
    digest.update("\0");
    digest.update(readFileSync(file));
  }

  const stamp = {
    builtAt: new Date().toISOString(),
    obfuscated: !skipObfuscate,
    fileCount: jsFiles.length,
    digest: digest.digest("hex").slice(0, 16),
  };
  writeFileSync(
    path.join(outDir, "release-manifest.json"),
    `${JSON.stringify(stamp, null, 2)}\n`,
  );
  writeFileSync(
    path.join(outDir, "README.md"),
    [
      "# Public release bundle",
      "",
      "Generated by `node scripts/build-release.mjs`.",
      "Do not edit by hand — regenerate from source.",
      "",
      `Built: ${stamp.builtAt}`,
      `Obfuscated: ${stamp.obfuscated}`,
      "",
    ].join("\n"),
  );

  console.log(
    `release/ ready (${stamp.fileCount} JS modules, obfuscated=${stamp.obfuscated})`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
