#!/usr/bin/env node
/**
 * Build obfuscated static assets into ./release for the public Pages deploy.
 *
 * Source under src/, lib/, styles/, vendor/ stays readable in the public repo.
 * release/ is what GitHub Pages serves (harder casual reverse-engineering).
 *
 * Usage:
 *   node scripts/build-release.mjs
 *   node scripts/build-release.mjs --skip-obfuscate   # copy only (CI smoke)
 */

import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { minify } from "terser";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "release");
const skipObfuscate = process.argv.includes("--skip-obfuscate");

/** Shipped as-is (not mangled). Heavy PDK trees stay out of Pages. */
const COPY_AS_IS = ["index.html", ".nojekyll", "styles", "lib", "vendor"];

async function obfuscateJsFile(sourcePath, destPath) {
  const code = readFileSync(sourcePath, "utf8");
  if (skipObfuscate) {
    writeFileSync(destPath, code);
    return;
  }
  const result = await minify(code, {
    compress: { passes: 2, dead_code: true },
    mangle: { toplevel: true },
    format: { comments: false },
    module: true,
  });
  if (!result.code) {
    throw new Error(`terser produced empty output for ${sourcePath}`);
  }
  writeFileSync(destPath, result.code);
}

function walkJsFiles(dir, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walkJsFiles(full, acc);
    else if (name.endsWith(".js") || name.endsWith(".mjs")) acc.push(full);
  }
  return acc;
}

function copyTree(rel) {
  const from = path.join(root, rel);
  const to = path.join(outDir, rel);
  if (!existsSync(from)) return;
  mkdirSync(path.dirname(to), { recursive: true });
  cpSync(from, to, { recursive: true });
}

async function main() {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  for (const rel of COPY_AS_IS) {
    console.log(`copy ${rel}`);
    copyTree(rel);
  }

  // Lightweight models README only (not full PDK checkouts).
  const modelsReadme = path.join(root, "models", "README.md");
  if (existsSync(modelsReadme)) {
    mkdirSync(path.join(outDir, "models"), { recursive: true });
    cpSync(modelsReadme, path.join(outDir, "models", "README.md"));
  }

  const jsFiles = walkJsFiles(path.join(root, "src"));
  const digest = createHash("sha256");
  for (const file of jsFiles) {
    const rel = path.relative(root, file);
    const dest = path.join(outDir, rel);
    mkdirSync(path.dirname(dest), { recursive: true });
    console.log(`${skipObfuscate ? "copy" : "minify"} ${rel}`);
    await obfuscateJsFile(file, dest);
    digest.update(rel);
    digest.update("\0");
    digest.update(readFileSync(file));
  }

  const stamp = {
    builtAt: new Date().toISOString(),
    obfuscated: !skipObfuscate,
    fileCount: jsFiles.length,
    digest: digest.digest("hex").slice(0, 16),
  };
  writeFileSync(
    path.join(outDir, "release-manifest.json"),
    `${JSON.stringify(stamp, null, 2)}\n`,
  );

  const licensePath = path.join(root, "LICENSE");
  if (existsSync(licensePath)) {
    cpSync(licensePath, path.join(outDir, "LICENSE"));
  }

  writeFileSync(path.join(outDir, "README.md"), buildReleaseReadme(stamp));

  console.log(
    `release/ ready (${stamp.fileCount} JS modules, obfuscated=${stamp.obfuscated})`,
  );
}

function buildReleaseReadme(stamp) {
  return `# SPICE Simulator

[![License: CC BY 4.0](https://img.shields.io/badge/License-CC%20BY%204.0-green?logo=creativecommons&logoColor=white)](https://creativecommons.org/licenses/by/4.0/)
[![JavaScript](https://img.shields.io/badge/javascript-ES%20modules-F7DF1E?logo=javascript&logoColor=black)](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
[![Version](https://img.shields.io/badge/version-0.1.0-blue?logo=semver&logoColor=white)](https://github.com/SJTU-YONGFU-RESEARCH-GRP/spice-simulator)

**Repository:** [SJTU-YONGFU-RESEARCH-GRP/spice-simulator](https://github.com/SJTU-YONGFU-RESEARCH-GRP/spice-simulator)

**Live demo:** [https://sjtu-yongfu-research-grp.github.io/spice-simulator/](https://sjtu-yongfu-research-grp.github.io/spice-simulator/)

Browser SPICE-like circuit simulator (DC, TRAN, AC, NOISE, TF, and more). This \`release/\` folder is the static site bundle published to GitHub Pages. The app is a **JavaScript platform**: simulation and UI state run in each user's browser so **circuit data stays with the individual** by default.

> Generated by \`node scripts/build-release.mjs\` (built ${stamp.builtAt}, obfuscated=${stamp.obfuscated}). Prefer editing the generator in \`scripts/build-release.mjs\` rather than this file by hand.

## Table of contents

- [Privacy and data retention](#privacy-and-data-retention)
- [Fork and self-host](#fork-and-self-host)
  - [Deploy on your own site (GitHub Pages)](#deploy-on-your-own-site-github-pages)
  - [Run on your local system](#run-on-your-local-system)
- [Features](#features)
- [Requirements](#requirements)
- [Project layout](#project-layout)
- [License](#license)

## Privacy and data retention

This project is built as a client-side **JS** app (vanilla ES modules), not a hosted multi-tenant backend for student circuits.

- Netlists, theme, and UI preferences are kept in the **browser** (\`localStorage\` on that machine / profile).
- The default engines (in-browser MNA and optional ngspice WASM) run **locally in the page**; your schematic text is not uploaded to our servers for simulation.
- Forking or cloning gives each person (or course site) an independent copy: **your data stays under your control** on your device or your own deployment.

Optional share-to-GitHub-Issue flows (when configured) are separate from simulation and only send what the user explicitly chooses to share.

## Fork and self-host

You can fork the public repo and run the same simulator on **your own site** or **your own machine**.

### Deploy on your own site (GitHub Pages)

1. Fork [SJTU-YONGFU-RESEARCH-GRP/spice-simulator](https://github.com/SJTU-YONGFU-RESEARCH-GRP/spice-simulator).
2. In the fork, enable **Settings → Pages → Build and deployment → GitHub Actions** (the workflow builds \`release/\` and publishes that folder).
3. Push to \`main\` / \`master\`, or run a release from the repo scripts if you need a versioned rebuild.
4. Open \`https://<your-github-user-or-org>.github.io/spice-simulator/\` (adjust the path if you rename the repo).

Anyone who forks gets a full static app they can brand or teach from without sending student netlists through a central third-party store.

### Run on your local system

From a clone of the **source** repo (recommended for development):

\`\`\`bash
git clone https://github.com/SJTU-YONGFU-RESEARCH-GRP/spice-simulator.git
cd spice-simulator
node scripts/serve.mjs
\`\`\`

Open [http://localhost:5173](http://localhost:5173). No \`npm install\` is required for day-to-day serving (devDependency \`terser\` is only needed to rebuild the obfuscated \`release/\` bundle).

To serve **this** \`release/\` folder as static files (same assets Pages uses):

\`\`\`bash
npx --yes serve release -p 5173
\`\`\`

Or point any static file server at \`release/\` and open \`index.html\`.

Smoke check from the repo root:

\`\`\`bash
node scripts/smoke.mjs
\`\`\`

## Features

| Area | Notes |
|------|--------|
| Analyses | \`.op\` / \`.dc\`, \`.tran\`, \`.ac\`, \`.noise\`, \`.tf\`, \`.pz\`, \`.disto\`, \`.mc\`, \`.four\`, \`.meas\`, \`.step\`, … |
| Engines | Default **JS** MNA; optional **ngspice** WASM worker |
| Devices | R L C V I D M Q E G F H S W B, \`K\`, \`X\` + \`.subckt\`, built-in \`OPAMP\` |
| UI | Waveforms, schematic view, CSV / VCD export helpers |

See the repository root [README.md](https://github.com/SJTU-YONGFU-RESEARCH-GRP/spice-simulator/blob/main/README.md) for the full analysis table and netlist notes.

## Requirements

- A modern browser with ES modules
- **Node.js** only if you serve or rebuild locally (\`node scripts/serve.mjs\`, \`npm run build:release\`)

## Project layout

\`\`\`text
release/
  index.html          UI shell
  src/                Obfuscated ES modules (Pages bundle)
  styles/             App CSS
  lib/                Sample library (e.g. models.cir)
  vendor/             ngspice WASM glue
  LICENSE             CC BY 4.0 notice (copied from repo root)
\`\`\`

Readable source lives in the parent repository (\`src/\`, \`scripts/\`, …). Regenerate this folder with:

\`\`\`bash
npm install
npm run build:release
\`\`\`

## License

Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). See [LICENSE](LICENSE).

Third-party assets (for example vendored ngspice) remain under their respective licenses.
`;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
